version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 818779533109.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building Docker image..."
      - docker build -t digital:latest .
      - echo "Build completed on `date`"
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push 818779533109.dkr.ecr.ap-south-1.amazonaws.com/project
